# Generated by Django 5.2.1 on 2026-05-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("belege", "0055_beleg_beleg_has_comment_true_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitstempel"),
                ),
                (
                    "username",
                    models.CharField(
                        default="unbekannt", max_length=100, verbose_name="Username"
                    ),
                ),
                ("payload", models.TextField(blank=True, null=True)),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entry",
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["created_at", "beleg"],
            },
        ),
    ]
