# Generated by Django 5.2.1 on 2026-08-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mylogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ["-created_at", "beleg"],
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
    ]
