# Generated by Django 5.2.1 on 2026-05-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BibliographicType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_type",
                    models.CharField(
                        choices=[
                            ("Literatur", "Literatur"),
                            ("Erhebung", "Erhebung"),
                            ("Sonstige", "Sonstige"),
                        ],
                        max_length=50,
                        verbose_name="Quelle Type",
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fachliteratur", "Fachliteratur"),
                            ("Journalit.Text", "Journalistischer Text"),
                            ("Literar.Text", "Literarischer Text"),
                            ("große_Fragebögen", "große Fragebögen"),
                            ("Ergänzungsfragebögen", "Ergänzungsfragebögen"),
                            ("Kundfahrten", "Kundfahrten"),
                            ("Fragebucherhebungen", "Fragebucherhebungen"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Quelle Subtype",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dissertation", "Dissertation"),
                            ("Gedichte", "Gedicht"),
                            ("Lexikon", "Lexikon"),
                            ("Lieder", "Lied"),
                            ("Prosa", "Prosa"),
                            ("Wiss.Zeitschrift", "Wissenschaftliche Zeitschrift"),
                            (
                                "Wiss.Zeitschriftenartikel",
                                "Wissenschaftlicher Zeitschriftenartikel",
                            ),
                            ("Wörterbuch", "Wörterbuch"),
                            ("Zeitung", "Zeitung"),
                            ("Sonstige", "Sonstige"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Quelle Spezifikation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Art der Quelle",
                "verbose_name_plural": "Arten der Quellen",
                "ordering": ["main_type", "sub_type", "specification"],
            },
        ),
        migrations.CreateModel(
            name="BibliographicItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        help_text="Sigle (ID). Darf nur einmal verwendet werden",
                        max_length=50,
                        verbose_name="Sigle",
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        help_text="Kurztitel", max_length=100, verbose_name="Kürzel"
                    ),
                ),
                (
                    "full_title",
                    models.CharField(
                        help_text="Volltitel", max_length=500, verbose_name="Titel"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Jahr"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="Angabe zum Band, z.B: 'Band 1: Italienisch–Deutsch' oder '[I. Heft] 2., verm. Aufl.'",
                        max_length=100,
                        null=True,
                        verbose_name="Band",
                    ),
                ),
                (
                    "author_last_name",
                    models.CharField(
                        blank=True,
                        help_text="Bei mehreren Autor*Innen: 'Benecke/Müller/Zarncke'",
                        max_length=150,
                        null=True,
                        verbose_name="Autor (Nachname)",
                    ),
                ),
                (
                    "author_first_name",
                    models.CharField(
                        blank=True,
                        help_text="Bei mehreren Autor*Innen 'Georg Friedrich/Wilhelm/Friedrich'",
                        max_length=100,
                        null=True,
                        verbose_name="Autor (Vorname)",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Bei mehreren Orten: 'Innsbruck / München'",
                        max_length=100,
                        null=True,
                        verbose_name="Ort",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        help_text="Verlag, z.B: 'De Gruyter' oder 'Dissertationen der Universität Wien'",
                        max_length=200,
                        null=True,
                        verbose_name="Verlag",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
                (
                    "in_zotero",
                    models.BooleanField(
                        default=False,
                        help_text="Wird automatisch gesetzt",
                        verbose_name="Zotero Eintrag vorhanden?",
                    ),
                ),
                (
                    "zotero_key",
                    models.URLField(
                        blank=True,
                        help_text="z.B. 'https://www.zotero.org/groups/12345/dboe/items/AWYHCEMA'",
                        max_length=150,
                        null=True,
                        verbose_name="Zotero URL",
                    ),
                ),
                (
                    "internal_node",
                    models.TextField(
                        blank=True, null=True, verbose_name="interne Anmerkung"
                    ),
                ),
                (
                    "bibl_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibls.bibliographictype",
                        verbose_name="Art der Quelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bibliographische Angabe",
                "verbose_name_plural": "Bibliographische Angaben",
                "ordering": ["sigle"],
            },
        ),
    ]
