# Generated by Django 5.2.1 on 2026-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliographicitem",
            name="author_first_name",
            field=models.CharField(
                blank=True,
                help_text="Bei mehreren Autor*Innen 'Georg Friedrich/Wilhelm/Friedrich'",
                max_length=100,
                null=True,
                verbose_name="Autor (Vorname)",
            ),
        ),
        migrations.AlterField(
            model_name="bibliographicitem",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Bei mehreren Orten: 'Innsbruck / München'",
                max_length=100,
                null=True,
                verbose_name="Ort",
            ),
        ),
        migrations.AlterField(
            model_name="bibliographicitem",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text="Verlag, z.B: 'De Gruyter' oder 'Dissertationen der Universität Wien'",
                max_length=200,
                null=True,
                verbose_name="Verlag",
            ),
        ),
    ]
