# Generated by Django 5.2.1 on 2026-05-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibls", "0002_alter_bibliographicitem_author_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliographicitem",
            name="full_title",
            field=models.CharField(
                help_text="Volltitel", max_length=500, verbose_name="Titel"
            ),
        ),
    ]
