# Generated by Django 5.2.1 on 2026-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibls", "0003_alter_bibliographicitem_full_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliographicitem",
            name="author_last_name",
            field=models.CharField(
                blank=True,
                help_text="Bei mehreren Autor*Innen: 'Benecke/Müller/Zarncke'",
                max_length=150,
                null=True,
                verbose_name="Autor (Nachname)",
            ),
        ),
    ]
