# Generated by Django 5.2.1 on 2026-02-17 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siglen", "0003_alter_sigle_orig_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sigle",
            name="bl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_bl",
                to="siglen.sigle",
                verbose_name="Bundesland",
            ),
        ),
        migrations.AlterField(
            model_name="sigle",
            name="gr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_gr",
                to="siglen.sigle",
                verbose_name="Großregion",
            ),
        ),
        migrations.AlterField(
            model_name="sigle",
            name="kr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_kr",
                to="siglen.sigle",
                verbose_name="Kleinregion",
            ),
        ),
    ]
