# Generated by Django 5.2.1 on 2026-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siglen", "0004_alter_sigle_bl_alter_sigle_gr_alter_sigle_kr"),
    ]

    operations = [
        migrations.AddField(
            model_name="belegsigle",
            name="name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Name"
            ),
        ),
    ]
