# Generated by Django 5.2.1 on 2025-06-05 08:46

import belege.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BelegSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dboe_id",
                    models.CharField(
                        blank=True,
                        help_text="The DBÖ ID",
                        max_length=250,
                        null=True,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "simple_xml",
                    belege.fields.XMLField(
                        blank=True, null=True, verbose_name="simplified XML"
                    ),
                ),
            ],
        ),
    ]
