# Generated by Django 5.2.1 on 2025-06-06 12:19

import belege.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beleg",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="The DBÖ ID",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "orig_xml",
                    belege.fields.XMLField(
                        blank=True, null=True, verbose_name="original tei-xml entry"
                    ),
                ),
                (
                    "xeno_data",
                    models.TextField(
                        blank=True, null=True, verbose_name="legacy transkription?"
                    ),
                ),
                (
                    "hauptlemma",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Hauptlemma"
                    ),
                ),
                (
                    "nebenlemma",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Nebenlemma"
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Subst", "Subst"),
                            ("Interj", "Interj"),
                            ("Verb", "Verb"),
                            ("Adj", "Adj"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="POS",
                    ),
                ),
            ],
        ),
    ]
