# Generated by Django 5.2.1 on 2025-06-08 09:22

import belege.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beleg",
            options={
                "ordering": ["dboe_id"],
                "verbose_name": "Beleg",
                "verbose_name_plural": "Belege",
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="archivzeile",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Archivzeile"
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="bibl",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Literatur"
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="quelle",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Quelle"
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="quelle_bearbeitet",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Quelle bearbeitet"
            ),
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="e.g. tu-10130.56",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="order number"),
                ),
                (
                    "orig_xml",
                    belege.fields.XMLField(verbose_name="original tei-cit node"),
                ),
                (
                    "quote_text",
                    models.TextField(blank=True, null=True, verbose_name="plain text"),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="definition"),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zitat",
                "verbose_name_plural": "Zitate",
                "ordering": ["beleg", "number"],
            },
        ),
    ]
