# Generated by Django 5.2.1 on 2025-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0002_alter_beleg_options_beleg_archivzeile_beleg_bibl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="import_issue",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if there was an issue during import",
                verbose_name="Import issue",
            ),
        ),
    ]
