# Generated by Django 5.2.1 on 2025-06-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0003_beleg_import_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="BundesLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        default="1", max_length=20, verbose_name="Bundesland"
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        default="OÖ", max_length=20, verbose_name="Kürzel"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Oberösterreich", max_length=50, verbose_name="Name"
                    ),
                ),
                (
                    "geonames",
                    models.URLField(
                        blank=True,
                        help_text="Link to corresponding GeoNames entry",
                        null=True,
                        verbose_name="GeoNames URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundesland",
                "verbose_name_plural": "Bundesländer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        default="5.4", max_length=20, verbose_name="Großregion"
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        default="Mühlv.", max_length=20, verbose_name="Kürzel"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Mühlviertel", max_length=50, verbose_name="Name"
                    ),
                ),
                (
                    "geonames",
                    models.URLField(
                        blank=True,
                        help_text="Link to corresponding GeoNames entry",
                        null=True,
                        verbose_name="GeoNames URL",
                    ),
                ),
                (
                    "bundesland",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.bundesland",
                        verbose_name="Bundesland",
                    ),
                ),
            ],
            options={
                "verbose_name": "Großregion",
                "verbose_name_plural": "Großregionen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        default="1", max_length=20, verbose_name="Kleinregion"
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        default="swestl.uMühlv.", max_length=20, verbose_name="Kürzel"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="südwestliches Mühlviertel",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "geonames",
                    models.URLField(
                        blank=True,
                        help_text="Link to corresponding GeoNames entry",
                        null=True,
                        verbose_name="GeoNames URL",
                    ),
                ),
                (
                    "bundesland",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.bundesland",
                        verbose_name="Bundesland",
                    ),
                ),
                (
                    "gregion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.gregion",
                        verbose_name="Großregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kleinregion",
                "verbose_name_plural": "Kleinregionen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(default="1", max_length=20, verbose_name="Ort"),
                ),
                (
                    "abbr",
                    models.CharField(
                        default="Bad Zell", max_length=20, verbose_name="Kürzel"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Bad Zell", max_length=50, verbose_name="Name"
                    ),
                ),
                (
                    "geonames",
                    models.URLField(
                        blank=True,
                        help_text="Link to corresponding GeoNames entry",
                        null=True,
                        verbose_name="GeoNames URL",
                    ),
                ),
                (
                    "bundesland",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.bundesland",
                        verbose_name="Bundesland",
                    ),
                ),
                (
                    "gregion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.gregion",
                        verbose_name="Großregion",
                    ),
                ),
                (
                    "kregion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.kregion",
                        verbose_name="Kleinregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
                "ordering": ["name"],
            },
        ),
    ]
