# Generated by Django 5.2.1 on 2025-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0004_bundesland_gregion_kregion_ort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ort",
            name="abbr",
        ),
        migrations.AlterField(
            model_name="kregion",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Name"),
        ),
    ]
