# Generated by Django 5.2.1 on 2025-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0005_remove_ort_abbr_alter_kregion_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gregion",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Name"),
        ),
    ]
