# Generated by Django 5.2.1 on 2025-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0006_alter_gregion_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundesland",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="ort",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Name"),
        ),
    ]
