# Generated by Django 5.2.1 on 2025-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0007_alter_bundesland_name_alter_ort_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundesland",
            name="abbr",
            field=models.CharField(default="OÖ", max_length=50, verbose_name="Kürzel"),
        ),
        migrations.AlterField(
            model_name="gregion",
            name="abbr",
            field=models.CharField(
                default="Mühlv.", max_length=50, verbose_name="Kürzel"
            ),
        ),
        migrations.AlterField(
            model_name="kregion",
            name="abbr",
            field=models.CharField(
                default="swestl.uMühlv.", max_length=50, verbose_name="Kürzel"
            ),
        ),
    ]
