# Generated by Django 5.2.1 on 2025-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0008_alter_bundesland_abbr_alter_gregion_abbr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ort",
            name="name",
            field=models.CharField(default="", max_length=250, verbose_name="Name"),
        ),
    ]
