# Generated by Django 5.2.1 on 2025-06-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0009_alter_ort_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="ort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="belege.ort",
                verbose_name="Ort",
            ),
        ),
    ]
