# Generated by Django 5.2.1 on 2025-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0010_beleg_ort"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundesland",
            name="coordinages",
            field=models.JSONField(blank=True, null=True, verbose_name="Koordinaten"),
        ),
        migrations.AddField(
            model_name="gregion",
            name="coordinages",
            field=models.JSONField(blank=True, null=True, verbose_name="Koordinaten"),
        ),
        migrations.AddField(
            model_name="kregion",
            name="coordinages",
            field=models.JSONField(blank=True, null=True, verbose_name="Koordinaten"),
        ),
        migrations.AddField(
            model_name="ort",
            name="coordinages",
            field=models.JSONField(blank=True, null=True, verbose_name="Koordinaten"),
        ),
        migrations.AlterField(
            model_name="bundesland",
            name="sigle",
            field=models.CharField(
                default="1", help_text="whatever", max_length=20, verbose_name="Sigle"
            ),
        ),
        migrations.AlterField(
            model_name="gregion",
            name="sigle",
            field=models.CharField(default="5.4", max_length=20, verbose_name="Sigle"),
        ),
        migrations.AlterField(
            model_name="kregion",
            name="sigle",
            field=models.CharField(default="1", max_length=20, verbose_name="Sigle"),
        ),
        migrations.AlterField(
            model_name="ort",
            name="sigle",
            field=models.CharField(default="1", max_length=20, verbose_name="Sigle"),
        ),
    ]
