# Generated by Django 5.2.1 on 2025-06-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0011_bundesland_coordinages_gregion_coordinages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bundesland",
            old_name="coordinages",
            new_name="coordinates",
        ),
        migrations.RenameField(
            model_name="gregion",
            old_name="coordinages",
            new_name="coordinates",
        ),
        migrations.RenameField(
            model_name="kregion",
            old_name="coordinages",
            new_name="coordinates",
        ),
        migrations.RenameField(
            model_name="ort",
            old_name="coordinages",
            new_name="coordinates",
        ),
    ]
