# Generated by Django 5.2.1 on 2025-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0012_rename_coordinages_bundesland_coordinates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facsimile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="whatever",
                        max_length=250,
                        unique=True,
                        verbose_name="Dateiname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faksimile",
                "verbose_name_plural": "Faksimiles",
                "ordering": ["file_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="citation",
            options={
                "ordering": ["beleg", "number"],
                "verbose_name": "Kontext",
                "verbose_name_plural": "Kontexte",
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="facsimile",
            field=models.ManyToManyField(
                blank=True,
                help_text="whatever",
                null=True,
                related_name="belege",
                to="belege.facsimile",
                verbose_name="Faksimiles",
            ),
        ),
    ]
