# Generated by Django 5.2.1 on 2025-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0013_facsimile_alter_citation_options_beleg_facsimile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beleg",
            name="facsimile",
            field=models.ManyToManyField(
                blank=True,
                help_text="whatever",
                related_name="belege",
                to="belege.facsimile",
                verbose_name="Faksimiles",
            ),
        ),
    ]
