# Generated by Django 5.2.1 on 2025-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0014_alter_beleg_facsimile"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="definition_lang",
            field=models.CharField(
                blank=True,
                choices=[("bar", "bar"), ("de", "de")],
                max_length=3,
                null=True,
                verbose_name="Sprache (Definition)",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="fragebogen_nummer",
            field=models.TextField(
                blank=True,
                help_text="Whatever",
                null=True,
                verbose_name="Fragebogen Nummer",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="interpration",
            field=models.TextField(
                blank=True,
                help_text="Summarizes a specific interpretative annotation which can be linked to a span of text",
                null=True,
                verbose_name="interpretation",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="note_anmerkung_b",
            field=models.TextField(
                blank=True, help_text="Whatever", null=True, verbose_name="Anmerkung: B"
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="note_anmerkung_o",
            field=models.TextField(
                blank=True, help_text="Whatever", null=True, verbose_name="Anmerkung: O"
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="quote_lang",
            field=models.CharField(
                blank=True,
                choices=[("bar", "bar"), ("de", "de")],
                max_length=3,
                null=True,
                verbose_name="Sprache (Kontext)",
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="definition",
            field=models.CharField(blank=True, null=True, verbose_name="definition"),
        ),
    ]
