# Generated by Django 5.2.1 on 2025-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0015_citation_definition_lang_citation_fragebogen_nummer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="p_ref",
            field=models.CharField(
                blank=True,
                help_text="whatever",
                null=True,
                verbose_name="Pronunciation reference",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="quote_gram",
            field=models.CharField(
                blank=True,
                help_text="whatever",
                max_length=250,
                null=True,
                verbose_name="Grammatik",
            ),
        ),
    ]
