# Generated by Django 5.2.1 on 2025-07-02 06:10

import belege.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0016_citation_p_ref_citation_quote_gram"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lautung",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="e.g. tu-10130.56",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Order number"),
                ),
                (
                    "orig_xml",
                    belege.fields.XMLField(
                        help_text="tei:form[@type='lautung'] node",
                        verbose_name="XML Node",
                    ),
                ),
                (
                    "pron",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Pronunciation",
                    ),
                ),
                (
                    "pron_lang",
                    models.CharField(
                        blank=True,
                        choices=[("bar", "bar"), ("de", "de")],
                        max_length=3,
                        null=True,
                        verbose_name="Sprache (Pronunciation)",
                    ),
                ),
                (
                    "pron_gram",
                    models.CharField(
                        blank=True,
                        help_text="whatever",
                        max_length=250,
                        null=True,
                        verbose_name="Grammatik",
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lautungen",
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
            ],
        ),
    ]
