# Generated by Django 5.2.1 on 2025-07-02 07:14

import belege.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0017_lautung"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lautung",
            options={
                "ordering": ["beleg", "number"],
                "verbose_name": "Lautung",
                "verbose_name_plural": "Lautungen",
            },
        ),
        migrations.AlterField(
            model_name="citation",
            name="definition",
            field=models.TextField(blank=True, null=True, verbose_name="definition"),
        ),
        migrations.CreateModel(
            name="Sense",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="e.g. tu-10130.56",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Order number"),
                ),
                (
                    "orig_xml",
                    belege.fields.XMLField(
                        help_text="tei:sense node", verbose_name="XML Node"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="definition"),
                ),
                (
                    "definition_lang",
                    models.CharField(
                        blank=True,
                        choices=[("bar", "bar"), ("de", "de")],
                        max_length=3,
                        null=True,
                        verbose_name="Sprache (Definition)",
                    ),
                ),
                (
                    "note_anmerkung_o",
                    models.TextField(
                        blank=True,
                        help_text="Whatever",
                        null=True,
                        verbose_name="Anmerkung: O",
                    ),
                ),
                (
                    "note_anmerkung_b",
                    models.TextField(
                        blank=True,
                        help_text="Whatever",
                        null=True,
                        verbose_name="Anmerkung: B",
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bedeutungen",
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bedeutung",
                "verbose_name_plural": "Bedeutungen",
                "ordering": ["beleg", "number"],
            },
        ),
    ]
