# Generated by Django 5.2.1 on 2025-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0018_alter_lautung_options_alter_citation_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sense",
            name="corresp_to",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Korrespondiert zu"
            ),
        ),
    ]
