# Generated by Django 5.2.1 on 2025-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0019_sense_corresp_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="ref_type_dbo",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Verweis (ref/@type='dbo')",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="ref_type_sni",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Verweis (ref/@type='sni')",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="xr_type_verweise",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Verweis (xr/@type='verweise')",
            ),
        ),
    ]
