# Generated by Django 5.2.1 on 2025-07-04 07:16

import belege.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0020_beleg_ref_type_dbo_beleg_ref_type_sni_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZusatzLemma",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="e.g. tu-10130.56",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Order number"),
                ),
                (
                    "orig_xml",
                    belege.fields.XMLField(
                        help_text="tei:form[@type='lautung'] node",
                        verbose_name="XML Node",
                    ),
                ),
                (
                    "form_orth",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Lemma"
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Subst", "Subst"),
                            ("Interj", "Interj"),
                            ("Verb", "Verb"),
                            ("Adj", "Adj"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="POS",
                    ),
                ),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zusatz_lemma",
                        to="belege.citation",
                        verbose_name="Citation",
                    ),
                ),
            ],
        ),
    ]
