# Generated by Django 5.2.1 on 2025-07-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0021_zusatzlemma"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zusatzlemma",
            options={
                "ordering": ["citation", "number"],
                "verbose_name": "Zusatzlemma",
                "verbose_name_plural": "Zusatzlemmata",
            },
        ),
    ]
