# Generated by Django 5.2.1 on 2025-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0024_alter_zusatzlemma_gram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="xr_type_verweise",
        ),
        migrations.AddField(
            model_name="beleg",
            name="xr_type_verweise_b",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Verweis (xr/@type='verweise' and @resp='B')",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="xr_type_verweise_o",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Verweis (xr/@type='verweise' and @resp='O')",
            ),
        ),
    ]
