# Generated by Django 5.2.1 on 2025-07-07 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0025_remove_beleg_xr_type_verweise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="zitierweise",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Zitierweise",
            ),
        ),
    ]
