# Generated by Django 5.2.1 on 2025-07-08 11:53

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0026_beleg_zitierweise"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="fragebogen_nummer",
            field=models.TextField(
                blank=True,
                help_text="Whatever",
                null=True,
                verbose_name="Fragebogen Nummer",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="note_diverse",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Anmerkung (diverse)",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="zitierweise",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Zitierweise",
            ),
        ),
    ]
