# Generated by Django 5.2.1 on 2025-07-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0027_beleg_fragebogen_nummer_beleg_note_diverse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnmerkungLautung",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="Kombination of the Beleg-ID and the @n",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Order number"),
                ),
                (
                    "resp",
                    models.CharField(
                        choices=[("O", "O"), ("B", "B")],
                        default="O",
                        help_text="whatever",
                        max_length=1,
                        verbose_name="Responsible (O/B)",
                    ),
                ),
                (
                    "corresp_to",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Korrespondiert zu",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Anmerkung"),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_lautung",
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anmerkung (Lautung)",
                "verbose_name_plural": "Anmerkungen (Lautung)",
                "ordering": ["beleg", "number"],
            },
        ),
    ]
