# Generated by Django 5.2.1 on 2025-07-09 13:28

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0028_anmerkunglautung"),
    ]

    operations = [
        migrations.AddField(
            model_name="anmerkunglautung",
            name="p_ref",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="Iindicates a reference to the pronunciation(s) of the headword",
                size=None,
                verbose_name="Pronunciation reference",
            ),
        ),
    ]
