# Generated by Django 5.2.1 on 2025-07-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0030_lehnwort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lehnwort",
            name="beleg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lehnwoerter",
                to="belege.beleg",
                verbose_name="Beleg",
            ),
        ),
    ]
