# Generated by Django 5.2.1 on 2025-07-10 08:02

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0031_alter_lehnwort_beleg"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="etym",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Etymologie",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="note_notabene",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Notabene",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="quelle_page",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Seite"
            ),
        ),
    ]
