# Generated by Django 5.2.1 on 2025-09-25 10:10

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0032_beleg_etym_beleg_note_notabene_beleg_quelle_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="definition_corresp",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Definition korrespondiert zu Kontext",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="archivzeile",
            field=models.CharField(
                blank=True,
                help_text="No helptext provided",
                max_length=250,
                null=True,
                verbose_name="Archivzeile",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="bibl",
            field=models.CharField(
                blank=True,
                help_text="No helptext provided",
                max_length=250,
                null=True,
                verbose_name="Literatur",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="dboe_id",
            field=models.CharField(
                help_text="No help text provided",
                max_length=250,
                primary_key=True,
                serialize=False,
                verbose_name="Beleg ID",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="hauptlemma",
            field=models.CharField(
                blank=True,
                help_text="Hauptlemma' beinhaltet sämtliche Einträge (inklusive Komposita und Wortbildungsvarianten), die einem bestimmten Lemma zugeordnet werden können",
                max_length=250,
                null=True,
                verbose_name="Hauptlemma",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="nebenlemma",
            field=models.CharField(
                blank=True,
                help_text="Ein Nebenlemma ist einem Hauptlemma zugeordnet. Das Nebenlemma teilt sich mit dem übergeordneten Hauptlemma (in weiten Teilen) den historisch-etymologischen Lemmaansatz, kann jedoch in anderer Hinsicht (z.B. Schreibung, Lautung) vom Hauptlemma abweichen.",
                max_length=250,
                null=True,
                verbose_name="Nebenlemma",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Subst", "Subst"),
                    ("Interj", "Interj"),
                    ("Verb", "Verb"),
                    ("Adj", "Adj"),
                ],
                help_text="Diese Angabe benennt die Wortart des jeweiligen Belegs.",
                max_length=20,
                null=True,
                verbose_name="Part of Speech",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="quelle",
            field=models.CharField(
                blank=True,
                help_text="No helptext provided",
                max_length=250,
                null=True,
                verbose_name="Quelle",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="zitierweise",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="No helptext provided",
                size=None,
                verbose_name="Zitierweise",
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="definition",
            field=models.TextField(
                blank=True,
                help_text='Diese Information beschreibt die Bedeutung des in Spalte "Belegsatz 1", "Belegsatz 2" etc. angegebenen Belegsatze',
                null=True,
                verbose_name="Bedeutung des Kontexts",
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="quote_text",
            field=models.TextField(
                blank=True,
                help_text="No help text provided",
                null=True,
                verbose_name="Kontext",
            ),
        ),
        migrations.AlterField(
            model_name="lautung",
            name="pron",
            field=models.CharField(
                blank=True,
                help_text="Die angegebene Information umfasst die lautliche Transkription des vorliegenden Belegs.",
                max_length=250,
                null=True,
                verbose_name="Lautung",
            ),
        ),
        migrations.AlterField(
            model_name="lautung",
            name="pron_gram",
            field=models.CharField(
                blank=True,
                help_text="No help text provided",
                max_length=250,
                null=True,
                verbose_name="Grammatikangabe zur Lautung",
            ),
        ),
        migrations.AlterField(
            model_name="lautung",
            name="pron_lang",
            field=models.CharField(
                blank=True,
                choices=[("bar", "bar"), ("de", "de")],
                help_text="No help text provided",
                max_length=3,
                null=True,
                verbose_name="Sprache (Lautung)",
            ),
        ),
        migrations.AlterField(
            model_name="lehnwort",
            name="pron",
            field=models.CharField(
                blank=True,
                help_text="no help text provided",
                max_length=250,
                null=True,
                verbose_name="Lehnwort",
            ),
        ),
        migrations.AlterField(
            model_name="sense",
            name="definition",
            field=models.TextField(
                blank=True,
                help_text="Diese Information beschreibt die Bedeutung der Lautungsangabe auf dem Beleg.",
                null=True,
                verbose_name="Bedeutung der Lautung",
            ),
        ),
    ]
