# Generated by Django 5.2.1 on 2025-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0033_citation_definition_corresp_alter_beleg_archivzeile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="xr",
            field=models.CharField(
                blank=True,
                help_text="Contains a phrase, sentence, or icon referring the reader to some other location in this or another text",
                max_length=300,
                null=True,
                verbose_name="Cross-reference phrase",
            ),
        ),
    ]
