# Generated by Django 5.2.1 on 2025-09-29 11:38

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0034_citation_xr"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="note_diverse",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="whatever",
                size=None,
                verbose_name="Anmerkung (diverse)",
            ),
        ),
    ]
