# Generated by Django 5.2.1 on 2025-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0035_citation_note_diverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="corresp",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Korrespondiert zu"
            ),
        ),
    ]
