# Generated by Django 5.2.1 on 2025-10-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0037_belegflatten"),
    ]

    operations = [
        migrations.AddField(
            model_name="belegflatten",
            name="dv_lt_star",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="DV/LT*"
            ),
        ),
        migrations.AlterField(
            model_name="belegflatten",
            name="dboe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flatten_beleg",
                to="belege.beleg",
                verbose_name="Beleg",
            ),
        ),
    ]
