# Generated by Django 5.2.1 on 2025-10-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0038_belegflatten_dv_lt_star_alter_belegflatten_dboe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="ort",
        ),
        migrations.CreateModel(
            name="GeoRelationBundesland",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corresp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@corrsp"
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@resp"
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.beleg"
                    ),
                ),
                (
                    "ort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.bundesland",
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoRelation Bundesland",
                "verbose_name_plural": "GeoRelation Bundesländer",
                "ordering": ["ort"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="bundesland",
            field=models.ManyToManyField(
                blank=True,
                through="belege.GeoRelationBundesland",
                to="belege.bundesland",
                verbose_name="Bundesland",
            ),
        ),
        migrations.CreateModel(
            name="GeoRelationGregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corresp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@corrsp"
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@resp"
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.beleg"
                    ),
                ),
                (
                    "ort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.gregion"
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoRelation Großregion",
                "verbose_name_plural": "GeoRelation Großregionen",
                "ordering": ["ort"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="gregion",
            field=models.ManyToManyField(
                blank=True,
                through="belege.GeoRelationGregion",
                to="belege.gregion",
                verbose_name="Großregion",
            ),
        ),
        migrations.CreateModel(
            name="GeoRelationKregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corresp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@corrsp"
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@resp"
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.beleg"
                    ),
                ),
                (
                    "ort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.kregion"
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoRelation Kleinregion",
                "verbose_name_plural": "GeoRelation Kleinregionen",
                "ordering": ["ort"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="kregion",
            field=models.ManyToManyField(
                blank=True,
                through="belege.GeoRelationKregion",
                to="belege.kregion",
                verbose_name="Kleinregion",
            ),
        ),
        migrations.CreateModel(
            name="GeoRelationOrt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corresp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@corrsp"
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@resp"
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.beleg"
                    ),
                ),
                (
                    "ort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.ort"
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoRelation Ort",
                "verbose_name_plural": "GeoRelation Orte",
                "ordering": ["ort"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="ort",
            field=models.ManyToManyField(
                blank=True,
                through="belege.GeoRelationOrt",
                to="belege.ort",
                verbose_name="Ort",
            ),
        ),
    ]
