# Generated by Django 5.2.1 on 2025-10-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0039_remove_beleg_ort_georelationbundesland_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="belegflatten",
            name="dv_lt_star",
        ),
    ]
