# Generated by Django 5.2.1 on 2025-10-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0040_remove_belegflatten_dv_lt_star"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BelegFlatten",
        ),
    ]
