# Generated by Django 5.2.1 on 2025-10-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0041_delete_belegflatten"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="facsimile",
        ),
        migrations.CreateModel(
            name="BelegFacs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        default="system",
                        help_text="Name of user or script resposnible for linking Beleg to Facsimile",
                        max_length=250,
                        verbose_name="Responsible for linking",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the link was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the link was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="belege.beleg"
                    ),
                ),
                (
                    "facsimile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.facsimile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beleg-Facsimile Link",
                "verbose_name_plural": "Beleg-Facsimile Links",
                "ordering": ["beleg", "facsimile"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="facs",
            field=models.ManyToManyField(
                blank=True,
                help_text="whatever",
                related_name="belege",
                through="belege.BelegFacs",
                to="belege.facsimile",
                verbose_name="Faksimiles",
            ),
        ),
    ]
