# Generated by Django 5.2.1 on 2025-12-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0042_remove_beleg_facsimile_belegfacs_beleg_facs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="stores result of NLP processing",
                        null=True,
                        verbose_name="Annotated text",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Tool/Model used to process the data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kontext",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="belege.citation",
                        verbose_name="Kontext",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
                "ordering": ["kontext", "created_at"],
            },
        ),
    ]
