# Generated by Django 5.2.1 on 2025-12-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0043_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="source_field",
            field=models.CharField(
                default="quote_text",
                help_text="name of the field, the annotated text was derived from",
                max_length=250,
                verbose_name="Source field",
            ),
        ),
    ]
