# Generated by Django 5.2.1 on 2026-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0050_alter_beleg_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lautung",
            name="dboe_id",
            field=models.CharField(
                help_text="e.g. tu-112119.52",
                max_length=250,
                primary_key=True,
                serialize=False,
                verbose_name="DBÖ ID",
            ),
        ),
        migrations.AlterField(
            model_name="lehnwort",
            name="dboe_id",
            field=models.CharField(
                help_text="e.g. tu-112.38",
                max_length=250,
                primary_key=True,
                serialize=False,
                verbose_name="DBÖ ID",
            ),
        ),
    ]
