# Generated by Django 5.2.1 on 2026-03-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0051_alter_lautung_dboe_id_alter_lehnwort_dboe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="hauptlemma_norm",
            field=models.CharField(
                blank=True,
                help_text="Normalisiertes Hauptlemma",
                max_length=260,
                null=True,
                verbose_name="Hauptlemma (normalisiert)",
            ),
        ),
    ]
