# Generated by Django 5.2.1 on 2026-04-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0052_beleg_hauptlemma_norm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citation",
            name="orig_xml",
        ),
        migrations.RemoveField(
            model_name="lautung",
            name="orig_xml",
        ),
        migrations.RemoveField(
            model_name="lehnwort",
            name="orig_xml",
        ),
        migrations.RemoveField(
            model_name="sense",
            name="orig_xml",
        ),
        migrations.RemoveField(
            model_name="zusatzlemma",
            name="orig_xml",
        ),
    ]
