# Generated by Django 5.2.1 on 2026-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0053_remove_citation_orig_xml_remove_lautung_orig_xml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="has_internal_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beleg",
            name="internal_comment",
            field=models.TextField(
                blank=True,
                help_text="Feld für interne Anmerkungen",
                null=True,
                verbose_name="interne Kommentare",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Subst", "Substantiv"),
                    ("Interj", "Interjektion"),
                    ("Verb", "Verb"),
                    ("Adj", "Adjektiv"),
                    ("Pron", "Pronomen"),
                    ("Adv", "Adverb"),
                    ("Prep", "Präposition"),
                    ("Conj", "Konjunktion"),
                    ("Num", "Numeral"),
                ],
                help_text="Diese Angabe benennt die Wortart des jeweiligen Belegs.",
                max_length=20,
                null=True,
                verbose_name="Part of Speech",
            ),
        ),
        migrations.AlterField(
            model_name="zusatzlemma",
            name="gram",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Subst", "Substantiv"),
                    ("Interj", "Interjektion"),
                    ("Verb", "Verb"),
                    ("Adj", "Adjektiv"),
                    ("Pron", "Pronomen"),
                    ("Adv", "Adverb"),
                    ("Prep", "Präposition"),
                    ("Conj", "Konjunktion"),
                    ("Num", "Numeral"),
                ],
                max_length=250,
                null=True,
                verbose_name="Grammatik",
            ),
        ),
        migrations.AlterField(
            model_name="zusatzlemma",
            name="pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Subst", "Substantiv"),
                    ("Interj", "Interjektion"),
                    ("Verb", "Verb"),
                    ("Adj", "Adjektiv"),
                    ("Pron", "Pronomen"),
                    ("Adv", "Adverb"),
                    ("Prep", "Präposition"),
                    ("Conj", "Konjunktion"),
                    ("Num", "Numeral"),
                ],
                max_length=20,
                null=True,
                verbose_name="POS",
            ),
        ),
    ]
