# Generated by Django 5.2.1 on 2026-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0012_alter_collection_options"),
        ("belege", "0054_beleg_has_internal_comment_beleg_internal_comment_and_more"),
        ("siglen", "0004_alter_sigle_bl_alter_sigle_gr_alter_sigle_kr"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(
                condition=models.Q(("has_internal_comment", True)),
                fields=["dboe_id"],
                name="beleg_has_comment_true_idx",
            ),
        ),
    ]
