# Generated by Django 5.2.1 on 2026-05-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0055_beleg_beleg_has_comment_true_idx"),
        ("bibls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="quelle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bibls.bibliographictype",
            ),
        ),
    ]
