# Generated by Django 5.2.1 on 2026-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0056_beleg_quelle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="year",
            field=models.CharField(
                blank=True,
                help_text="No helptext provided",
                max_length=250,
                null=True,
                verbose_name="Jahr",
            ),
        ),
    ]
