# Generated by Django 5.2.1 on 2026-07-07 11:56

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0057_beleg_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="facs",
        ),
        migrations.AddField(
            model_name="beleg",
            name="scan",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=350, null=True),
                blank=True,
                default=list,
                help_text="Scans",
                size=None,
                verbose_name="Scans",
            ),
        ),
        migrations.DeleteModel(
            name="BelegFacs",
        ),
        migrations.DeleteModel(
            name="Facsimile",
        ),
    ]
