# Generated by Django 5.2.1 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0012_alter_collection_options"),
        ("belege", "0058_remove_beleg_facs_beleg_scan_delete_belegfacs_and_more"),
        ("bibls", "0001_initial"),
        ("siglen", "0004_alter_sigle_bl_alter_sigle_gr_alter_sigle_kr"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="has_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(
                condition=models.Q(("has_scan", True)),
                fields=["dboe_id"],
                name="beleg_has_scan_true_idx",
            ),
        ),
    ]
