# Generated by Django 5.2.1 on 2026-08-21 07:53

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0059_beleg_has_scan_beleg_beleg_has_scan_true_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="note",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores any kind of ./tei:note",
                null=True,
                verbose_name="tei:note",
            ),
        ),
    ]
