# Generated by Django 5.2.1 on 2026-08-22 06:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0060_beleg_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="xr",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores any kind of ./tei:xr",
                null=True,
                verbose_name="tei:xr",
            ),
        ),
    ]
