# Generated by Django 5.2.1 on 2026-08-22 15:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0061_beleg_xr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="etym",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="note_diverse",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="note_notabene",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="xr_type_verweise_b",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="xr_type_verweise_o",
        ),
        migrations.AddField(
            model_name="beleg",
            name="etymology",
            field=django_jsonform.models.fields.JSONField(
                blank=True, help_text="whatever", null=True, verbose_name="Etymologie"
            ),
        ),
        migrations.DeleteModel(
            name="AnmerkungLautung",
        ),
    ]
