# Generated by Django 5.2.1 on 2026-08-24 05:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0062_remove_beleg_etym_remove_beleg_note_diverse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citation",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="definition_lang",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="note_anmerkung_b",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="note_anmerkung_o",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="note_diverse",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="xr",
        ),
        migrations.AddField(
            model_name="citation",
            name="definition_node",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text='Diese Information beschreibt die Bedeutung des in Spalte "Belegsatz 1", "Belegsatz 2" etc. angegebenen Belegsatze',
                null=True,
                verbose_name="Bedeutung des Kontexts (tei:def)",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="note",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores any kind of ./tei:note",
                null=True,
                verbose_name="tei:note",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="xr_node",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores any kind of ./tei:xr",
                null=True,
                verbose_name="tei:xr",
            ),
        ),
    ]
