# Generated by Django 5.2.1 on 2026-08-24 06:46

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("belege", "0063_remove_citation_definition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sense",
            name="note_anmerkung_b",
        ),
        migrations.RemoveField(
            model_name="sense",
            name="note_anmerkung_o",
        ),
        migrations.AddField(
            model_name="sense",
            name="note",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores any kind of ./tei:note",
                null=True,
                verbose_name="tei:note",
            ),
        ),
    ]
