# Generated by Django 5.2.1 on 2026-08-24 08:38

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0064_remove_citation_definition_corresp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citation",
            name="definition_corresp",
        ),
        migrations.AddField(
            model_name="citation",
            name="re_node",
            field=django_jsonform.models.fields.JSONField(
                blank=True, help_text="Zusatzlemma", null=True, verbose_name="tei:re"
            ),
        ),
    ]
