# Generated by Django 5.2.1 on 2026-08-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0065_remove_citation_definition_corresp_citation_re_node"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZusatzLemma",
        ),
    ]
