# Generated by Django 5.2.1 on 2026-08-28 07:33

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0066_delete_zusatzlemma"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="place_qdb",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="No helptext provided",
                size=None,
                verbose_name="Ort (QDB)",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="place_qu",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="No helptext provided",
                size=None,
                verbose_name="Ort (QU)",
            ),
        ),
    ]
