# Generated by Django 5.2.1 on 2026-09-08 07:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0067_beleg_place_qdb_beleg_place_qu"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="ref",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores tei:ref with different @type values",
                null=True,
                verbose_name="tei:ref",
            ),
        ),
    ]
