# Generated by Django 2.1.1 on 2022-06-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_es_document_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(name__in=['distribution', 'sense', 'multi_word_expression', 'etymology', 'compound', 'lemma']), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='annotations.Category', verbose_name='Category'),
        ),
    ]
