# Generated by Django 2.1.1 on 2023-05-11 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0004_add_category_prop_to_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='es_document',
            name='xml_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user updated the xml field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xml_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
