# Generated by Django 5.2.1 on 2025-12-11 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0007_alter_annotation_id_alter_autor_artikel_id_and_more"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS guardian_userobjectpermission;"),
        migrations.RunSQL("DROP TABLE IF EXISTS guardian_groupobjectpermission;"),
    ]
