# Generated by Django 5.2.1 on 2026-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0010_alter_annotation_options_alter_autor_artikel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["modified"]},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tag"),
        ),
    ]
