# Generated by Django 5.2.1 on 2026-03-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0011_alter_collection_options_alter_tag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-modified"]},
        ),
    ]
